### ISSUE TITLE
Cannot update with foundry v11

### ISSUE THREAD

**Issue by ChuckTheBoss** [Forgotten-Adventures/FA_Battlemaps#21]
**FoundryVTT version:** v11 build 315
**current fa-battlemaps version:** 1.0.63
**Replicate behavior:** Trying to update the module to the latest version in the "add-on modules" page of foundry. 
**error message:** An update is available for fa-battlemaps but it may not be installed because it requires a core software version 12 which is not yet stable.

As far as I can see from the patch notes, it looks like fa-battlemaps should be compatible with foundry v11, and has worked for me up until this point. This only really matters because I am trying to download "Illithinoch" (I'm running The Shattered Obelisk) and it requires at least v 1.1.x 
![Screenshot 2024-09-17 at 10 21 28 AM](https://github.com/user-attachments/assets/6ed85163-1a06-45a3-86bc-af20e7836bbd)

**Comment by sneat** [comment]
Hi @ChuckTheBoss - the issue is that the maps themselves are now being made in v12 of Foundry, and that's not backwards compatible with v11. Foundry supports migrating older content forward, but not newer content backwards. The team wanted to make use of some of the new features that are in v12, so made the decision to upgrade.

Hopefully you'll be able to upgrade to v12 yourself sooner rather than later too.
